CLI11: disable tests
When using meson subproject wrap builds, we get the following compile
error:

```
../subprojects/CLI11/include/CLI/Timer.hpp:112:12: error: ‘CLI::Timer& CLI::Timer::operator/(std::size_t)’ should return by value [-Werror=effc++]
  112 |     Timer &operator/(std::size_t val) {
```

This is due to the CLI11 dependency not setting options and the default
setting in their meson.build is to enable tests.  Those tests have
different compile warning expectations than our projects use.  Disable
the tests since there is no reason for us to run a subproject's unit
tests.

Change-Id: I60ecae255d5498e2588b7c4cbf9fd3746acbee77
Signed-off-by: Patrick Williams <patrick@stwcx.xyz>